language: php

php:
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update && composer --version
  - composer install

before_script:
  - chmod -R a+w runtime
  - mysql -e 'CREATE DATABASE bootstrap_yii2_tests;'
  - mysql -u root -e "CREATE USER 'bootstrap_yii2'@'localhost' IDENTIFIED BY '';"
  - mysql -u root -e "GRANT ALL ON bootstrap_yii2_tests.* TO 'bootstrap_yii2'@'localhost';"
  - php yii create-local-config --path=@app/config/local/main.php
  - composer test:build

script:
  - vendor/bin/codecept run --coverage-xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
